import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project Tracking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="app-root">
          <aside className="sidebar">
            <div className="p-1 flex flex-col gap-10 w-full">
              <div className="logo-wrap">
              <img src="/skf-logo.svg" alt="SKF" className="logo" />
            </div>
            <nav className="flex flex-col gap-6">
              <Link href="/" className="flex items-center gap-4 py-4 px-4 w-full rounded-xl hover:bg-white/10 text-white font-medium cursor-pointer">
                <img
                  src="/monitoring-icon.png"
                  alt="Monitoring Icon"
                  className="w-[36px] h-[36px] object-contain flex-shrink-0"
                />
                <span className="text-[17px] font-semibold whitespace-nowrap">Tracking</span>
              </Link>

              <Link href="/bom-cost" className="flex items-center gap-4 py-4 px-4 w-full rounded-xl hover:bg-white/20 text-white font-medium cursor-pointer">
              
                <img
                  src="/calculation.png"
                  alt="Calculation Icon"
                  className="w-[36px] h-[36px] object-contain flex-shrink-0"
                />
                <span className="text-[17px] font-semibold whitespace-nowrap">BOM Cost</span>
              </Link>
              <Link href="/bom-cost" className="flex items-center gap-4 py-4 px-4 w-full rounded-xl hover:bg-white/20 text-white font-medium cursor-pointer">
                Data BP
              </Link>
            </nav>
          </div>
        </aside>
        <main className="app-main">{children}</main>
      </div>
    </body>
  </html>
  );
}
