import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project Tracking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="app-root">
          <aside className="sidebar">
            <div className="p-1 flex flex-col gap-10 w-full">
              <div className="logo-wrap">
              <img src="/skf-logo.svg" alt="SKF" className="logo" />
            </div>
            <nav className="flex flex-col gap-4">
            {/* TRACKING */}
            <Link href="/" className="flex items-center gap-4 py-4 px-4 rounded-xl hover:bg-white/10 text-white">
              <img src="/monitoring-icon.png" className="w-9 h-9" />
              <span>Tracking</span>
            </Link>

            {/* BOM COST */}
            <div className="flex flex-col gap-2">
              <Link href="/bom-cost" className="flex items-center gap-4 py-4 px-4 rounded-xl hover:bg-white/20 text-white">
                <img src="/calculation.png" className="w-9 h-9" />
                <span>BOM Cost</span>
              </Link>

              {/* SUB MENU */}
              <Link
                href="/bom-cost/bp"
                className="ml-14 text-sm text-white/80 hover:text-white"
              >
                • Data BP
              </Link>
            </div>

          </nav>

          </div>
        </aside>
        <main className="app-main">{children}</main>
      </div>
    </body>
  </html>
  );
}
