import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project Tracking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="app-root">
          <aside className="sidebar">
            <div className="p-1 flex flex-col gap-10 w-full">
              <div className="logo-wrap">
              <img src="/skf-logo.svg" alt="SKF" className="logo" />
            </div>
           <nav className="flex flex-col gap-4">
          {/* TRACKING */}
          <Link
            href="/"
            className="flex items-center gap-4 py-4 px-4 w-full rounded-xl hover:bg-white/10 text-white font-medium"
          >
            <img
              src="/monitoring-icon.png"
              alt="Monitoring Icon"
              className="w-[36px] h-[36px] object-contain"
            />
            <span className="text-[17px] font-semibold">Tracking</span>
          </Link>

          {/* BOM COST (PARENT) */}
          <div className="flex flex-col gap-2">

            <div className="flex items-center gap-4 py-4 px-4 w-full rounded-xl text-white font-medium">
              <img
                src="/calculation.png"
                alt="Calculation Icon"
                className="w-[36px] h-[36px] object-contain"
              />
              <span className="text-[17px] font-semibold">BOM Cost</span>
            </div>

            {/* SUB MENU */}
            <div className="ml-14 flex flex-col gap-1">

              <Link
                href="/bom-cost"
                className="py-2 px-3 rounded-lg text-white/80 hover:bg-white/10 hover:text-white text-sm"
              >
                • BOM Cost
              </Link>

              <Link
                href="/bom-cost/bp"
                className="py-2 px-3 rounded-lg text-white/80 hover:bg-white/10 hover:text-white text-sm"
              >
                • Data BP
              </Link>

            </div>
          </div>

        </nav>

          </div>
        </aside>
        <main className="app-main">{children}</main>
      </div>
    </body>
  </html>
  );
}
